server.port=3305
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.web.resources.add-mappings=true
spring.web.resources.static-locations=classpath:/static/,classpath:/public/,file:///C:/hrms/uploads/,file:///D:/HRMS/Uploads/
